name: "Other"

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  other:
    name: "Other"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug event.json"
        if: ${{ always() }}
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Other 1"
        run: |
          echo "Ralph Did It!"

      #- name: "Docker Test Action"
      #  id: test
      #  uses: smashedr/docker-test-action@v1
      #  #with:
      #  #  token: ${{ secrets.GITHUB_TOKEN }}

      #- name: "Echo Outputs"
      #  run: |
      #    echo output: '${{ steps.test.outputs.sha }}'

      #- name: "Step 1"
      #  run: |
      #    echo step 1
      #    npm install --silent prettier

      #- name: "Step 2"
      #  run: |
      #    npx prettier --check .

      #- name: "Step 3"
      #  if: always()
      #  run: |
      #    prettier --check .
