name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Update Tags"
        uses: cssnr/update-version-tags-action@master

      - name: "Debug event.json"
        if: ${{ always() }}
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "not a release"
        if: ${{ github.event_name != 'release' }}
        run: |
          echo yes

      - name: "prerelease"
        if: ${{ github.event.release.prerelease }}
        run: |
          echo yes

      - name: "release"
        if: ${{ !github.event.release.prerelease }}
        run: |
          echo yes
