name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Update Tags"
        uses: cssnr/update-version-tags-action@master

      - name: "Debug event.json"
        if: ${{ always() }}
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "not a release"
        if: ${{ github.event_name != 'release' }}
        run: |
          echo yes

      - name: "prerelease"
        if: ${{ github.event.release.prerelease }}
        run: |
          echo yes

      - name: "release"
        if: ${{ !github.event.release.prerelease }}
        run: |
          echo yes

      - name: "Debug"
        if: ${{ always() }}
        run: |
          echo name: "${{ github.event.release.prerelease && 'testpypi' || 'pypi' }}"
          echo url: "https://${{ github.event.release.prerelease && 'test.' || '' }}pypi.org/p/actions-tools"
          echo GITHUB_REF_NAME: "${GITHUB_REF_NAME}"
