name: "Release"

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Debug event.json"
        if: ${{ always() }}
        run: |
          cat "${GITHUB_EVENT_PATH}"

      - name: "Debug"
        if: ${{ always() }}
        run: |
          echo "name: ${{ github.event.release.name }}"
          echo "tag_name: ${{ github.event.release.tag_name }}"
          echo "html_url: ${{ github.event.release.html_url }}"
          echo "body: ${{ github.event.release.body }}"

      - name: "1: Test Local Action"
        id: test
        uses: ./

      - name: "Update Version Tags"
        id: tags
        uses: cssnr/update-version-tags-action@master

      - name: "Debug Tags"
        run: |
          echo "tags: ${{ steps.tags.outputs.tags }}"

      - name: "not a release"
        if: ${{ github.event_name != 'release' }}
        run: |
          echo yes

      - name: "prerelease"
        if: ${{ github.event.release.prerelease }}
        run: |
          echo yes

      - name: "release"
        if: ${{ !github.event.release.prerelease }}
        run: |
          echo yes
